### PR TITLE
Fix a memory leak in downcast

### LINKED ISSUE #261: Memory leak in `Error::downcast` in failure 0.1.2
The following code quickly leaks memory:
```rust
#[macro_use]
extern crate failure;

use failure::Error;

#[derive(Debug, Fail)]
#[fail(display = "my custom failure type")]
struct MyFail;

fn main() {
    loop {
        Error::from(MyFail).downcast::<MyFail>().unwrap();
    }
}
```

This happens because [`Error::downcast`](https://docs.rs/crate/failure/0.1.2/source/src/error/error_impl.rs) does not drop the `Box<Inner<Fail>>` contained within the `Error`, it only drops the backtrace contained in that box and moves out the error type itself.

(Thanks to @rustonaut for finding the root cause!)

Note that I've not tested this on master, but on 0.1.2, which is the most up-to-date version published on Crates.io.

### PR DESCRIPTION
**Pull request by mitsuhiko**
This fixes #261 on newer Rust versions. I don't know of a way to fix it for olders.

The deprecation note for older Rusts is also the only way I know in which a user could be informed about this issue.

### CODE REVIEW

File: src/error/error_impl.rs [hunk 1]
```diff
@@ -49,8 +48,23 @@ impl ErrorImpl {
...
+                        let ptr = Box::into_raw(self.inner);
+                        dealloc(ptr as *mut u8, layout);
+                    }
+                }
+
+                // slightly leaky versions of the above thing which makes the box
+                // itself leak.  There is no good way around this as far as I know.
+                #[cfg(not(has_global_alloc))] {
+                    use core::mem;
+                    mem::forget(self);
```
Comment (little-dude) [inline src/error/error_impl.rs]: This is pure curiosity, but do you mind explaining why this leaks memory?

If I understand correctly, the `ptr::read(fail as *const T)` does a memcopy `T` and moves `T` out of its box without deallocating the box. But when we to `mem::forget(self)` why isn't the box's memory not deallocated?

Comment (mitsuhiko) [reply src/error/error_impl.rs]: `mem::forget` tells it not to run a destructor. By moving out the fields all inner fields were destroyed but the heap allocation for the containing struct in the box is forgotten and leaks.
